spring.application.name=platform
server.port=8080
spring.jpa.hibernate.ddl-auto=none
spring.kafka.bootstrap-servers=kafka:9092
spring.datasource.url=jdbc:postgresql://postgres-platform:5432/platform
spring.datasource.username=platform
spring.datasource.password=platform